CREATE TABLE IF NOT EXISTS GW_INSTANCE_STATUS (
  INSTANCE_ID VARCHAR(50) PRIMARY KEY,
  GROUP_ID VARCHAR(2),
  SERVER_PORT INTEGER,
  ACTIVE_URL VARCHAR(300),
  ACTIVE_TARGET VARCHAR(10),
  CHAT_OPEN BOOLEAN,
  EMAIL_OPEN BOOLEAN,
  READY BOOLEAN,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IX_GW_IS_01 ON GW_INSTANCE_STATUS (UPDATED_AT);
