gateway:
  instance:
    id: ${GATEWAY_INSTANCE_ID:WA1}
  # prod: all targets enabled.
  targets:
    U1: ws://127.0.0.1:6701/clientws/U1
    U2: ws://127.0.0.1:6702/clientws/U2
    A1: ws://127.0.0.1:6703/clientws/A1
    A2: ws://127.0.0.1:6704/clientws/A2
  ring:
    G1: U1,U2,A1,A2
    G2: A1,A2,U1,U2
  recover:
    enabled: true
    G1: U1,U2
    G2: A1,A2
  prefer:
    enabled: true
    G1: U1,U2
    G2: A1,A2
